mqtt:
    host:
    port:
    user:
    password:
#    discovery_prefix: homeassistant #change to match with setting of home-assistant
sensors:
    -
        id:
#        name: #defaults to an unsanitized version of the id paramater
        pin: # GPIO pin
        interval: # time between sending updates in minutes
        state_topic: "home-assistant/sensor"
        # discovery_values:
        #   -
        #     id:
        #     name:
        #     template: # json format {{ value_json.humidity }}
        #     unit_of_measurement:
